### ISSUE TITLE
Docker Version > 19 Support

### ISSUE THREAD

**Issue by samedguener** [NTHU-LSALAB/KubeShare#10]
Hi all,

thanks again for the very interesting work!

Why is the support limited to Docker versions below 19? Is there any roadmap to support Docker > 19?

Best,
Samed

**Comment by jchou-git** [comment]
It is due to the version compatibility issue. We expect to solve this issue in a few months. Please check back soon.

**Comment by yanghaku** [comment]
So, does the current Kubeshare version support docker> 19.0?  (April 2, 2021)

**Comment by StarCoral** [comment]
yes, we support it.
In fact, 
you just need to enable the nvidia runtime as your default runtime on your node.

```
Runtimes: nvidia runc
Default Runtime: nvidia
```

**Comment by yanghaku** [comment]
Okay, thank you, but I'm still stuck in issue #9, could you help me answer it?
