### ISSUE TITLE
HPDC Slide

### ISSUE THREAD

**Issue by ZinuoCai** [NTHU-LSALAB/KubeShare#12]
Where can I find your presentation slide please? Thanks!

**Comment by jchou-git** [comment]
[HPDC KubeShare - Eric Final.pdf](https://github.com/NTHU-LSALAB/KubeShare/files/5656422/HPDC.KubeShare.-.Eric.Final.pdf)
Recorded video: https://www.youtube.com/watch?v=1WQMKCGN9j4

**Comment by ZinuoCai** [comment]
Thanks!
