### ISSUE TITLE
Some problems in installation

### ISSUE THREAD

**Issue by wangzhuang12306** [NTHU-LSALAB/KubeShare#14]
The url [https://lsalab.cs.nthu.edu.tw/~ericyeh/KubeShare/v0.9/crd.yaml](https://lsalab.cs.nthu.edu.tw/~ericyeh/KubeShare/v0.9/crd.yaml) is unreachable.

**Comment by jchou-git** [comment]
Our server is broken recently. we are trying to get it back online soon.

**Comment by StarCoral** [comment]
I updated the readme file.  You can find the `crd.yaml` in the `deploy` directory.

**Comment by wangzhuang12306** [comment]
> 
> 
> I updated the readme file. You can find the `crd.yaml` in the `deploy` directory.

Ok, thank you
