### ISSUE TITLE
nvidia-k8s-device-plugin can not find gpu cards

### ISSUE THREAD

**Issue by Iamlovingit** [NTHU-LSALAB/KubeShare#2]
Hi, I re-install docker and nvidia-docker, now the k8s can not find out gpu cards. It can work before I re-install the lower docker.
my nvidia-k8s-devcie-plugin version is 1.11
my docker version 18.06.3-ce
my nvidia-docker is 2.2.2
Could you show me your version? @ncy9371

**Comment by ncy9371** [comment]
Hi, list below: (ubuntu bionic)
k8s-device-plugin: [1.0.0-beta4](https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta4/nvidia-device-plugin.yml)
docker: 18.09.7
nvidia-docker2: 18.09.7
