### ISSUE TITLE
About how to write the gpu topology

### ISSUE THREAD

**Issue by icovej** [NTHU-LSALAB/KubeShare#25]
Hello, when I deploy KubeShare and test it, My pod is always in Pending. After I check the log, in kubeshare-scheduler.log, there is "No corresponding gpu NVIDIA GeForce GTX 3090 in the node master". 
My k8s cluster has only one node with two GPU devices. This is my kubeshare-config.yaml:
cellTypes:
  GTX3090-NODE:
    childCellType: "NVIDIA GeForce GTX 3090"
    childCellNumber: 1
    childCellPriority: 100
    isNodeLevel: true

cells:
- cellType: GTX3090-NODE
  cellChildren:
  - cellId: apple

I need your help. Plz @ncy9371 @justin0u0

**Comment by icovej** [comment]
The biggest question is when I create a pod, it's always in Pending and there is no events. I have installed all components and installed nvidia-device-plugin.

**Comment by justin0u0** [comment]
Hi @icovej, the `childCellType` should be joined with dashes.

You can refer to this comment for details: https://github.com/NTHU-LSALAB/KubeShare/issues/22#issuecomment-1325073356.

**Comment by icovej** [comment]
> the `childCellType` should be joined with dashes.
> 
> You can refer to this comment for details:

well, in fact, after I write this issue, I realized it. It's my wrong. But after I fix it, I still couldn't create a pod. In  kubeshare-scheduler.log, the error is "No corresponding gpu NVIDIA GeForce GTX 3090 in the node master".

How can I deal with it

**Comment by justin0u0** [comment]
The `cellId` part should match the node name with GPUs.

I think that is the problem causing the error.
