### ISSUE TITLE
how to test the runtime isolation of computing resource and memory？

### ISSUE THREAD

**Issue by koalaxiu7** [NTHU-LSALAB/KubeShare#5]
hi,
I want to test the runtime isolation of computing resource and memory, how to test the isolation and where are testcases for it? Thanks in advance!

**Comment by jchou-git** [comment]
We used detectron2 inference benchmark. To control the workload, we adjust the inter-arrival time of inference requests. For instance, you can increase the workload by reducing the inter-arrival time to force higher GPU utilization. By with our GPU isolation mechanism(Gemini), the GPU utilization should be bounded under the limit specified in YAML.
