### ISSUE TITLE
Scheduler issue

### ISSUE THREAD

**Issue by fatgleCheng** [NTHU-LSALAB/KubeShare#7]
在scheduler 計算Pod使用的資源總量時，有遇到可用資源變成負的情況。
目前的計算方式中似乎會把Completed的Pod所用到的資源也算進去。

**Comment by ncy9371** [comment]
Hi,
I did ignore the completed SharePod in free resource accounting but forgot to apply to Pod too.
And I don't know why ignoring the SharePods with restart policy Always too. I delete it now.
thanks!
https://github.com/NTHU-LSALAB/KubeShare/commit/8e624ec5c8c3b6629adc12273c220c42fadca3e8

**Comment by ncy9371** [comment]
new image pushed
